language: java
dist: bionic
services:
  - xvfb
sudo: false
git:
  depth: false
cache:
  directories:
  - $HOME/.m2
addons:
  sonarcloud:
    organization: "svenpeldszus-github" # the key of the org you chose at step #3
    token:
      secure: "cd98cdece5af7be16122005ca2c57dfa8812bccf" # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=SvenPeldszus_consistency-tgg-generator
